# Generated by Codex on 2026-01-28

import django.db.models.deletion
from django.db import migrations, models


def create_default_company(apps, schema_editor):
    Company = apps.get_model('users', 'Company')
    User = apps.get_model('users', 'User')
    default_company, _ = Company.objects.get_or_create(name="Default Company")
    User.objects.filter(company__isnull=True).update(company=default_company, role="EMPLOYEE")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'company',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='bonus_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='users', to='users.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ADMIN', 'Company admin')],
                                   default='EMPLOYEE', max_length=20),
        ),
        migrations.RunPython(create_default_company, migrations.RunPython.noop),
    ]
