# Generated by Codex on 2026-01-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_company_not_null'),
        ('tasks', '0004_task_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name='bonus_transactions', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='bonus_transactions', to='users.user')),
            ],
            options={
                'verbose_name': 'bonus_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
