# Generated by Django 5.2.1 on 2025-06-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'project',
                'ordering': ['created_at'],
            },
        ),
    ]
