# Generated by Codex on 2026-01-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_company(apps, schema_editor):
    Company = apps.get_model('users', 'Company')
    Project = apps.get_model('projects', 'Project')
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    default_company, _ = Company.objects.get_or_create(name="Default Company")
    for project in Project.objects.all():
        if project.user_id:
            user = User.objects.filter(id=project.user_id).first()
            if user and user.company_id:
                project.company_id = user.company_id
                project.created_by_id = user.id
                project.save(update_fields=["company", "created_by"])
                project.participants.add(user)
            else:
                project.company_id = default_company.id
                project.save(update_fields=["company"])
        else:
            project.company_id = default_company.id
            project.save(update_fields=["company"])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('users', '0003_company_bonus_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='projects', to='users.company'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='project_participants',
                                         to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_company, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='project',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
