services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.prod.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static:/app/static
      - media:/app/media
