services:
  db:
    image: postgres:17.5-alpine3.21
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=schedule_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1111
  web:
    command: sleep infinity
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    ports:
      - "8000-8010:8000-8010"
    environment:
      - POSTGRES_NAME=schedule_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1111
    depends_on:
      - db
  cache:
    image: redis:8.0-alpine3.21
    restart: always
    command: redis-server --save 120 1 --loglevel warning
    volumes:
      - ../cache:/data

volumes:
  db_data:


