# Generated by Django 5.2.1 on 2025-06-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
