# Generated by Django 5.2.1 on 2025-06-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=models.TextField(null=True),
        ),
    ]
