# Generated by Django 5.2.1 on 2025-06-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_page_content_en_page_content_ru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content_en',
            new_name='content_en_us',
        ),
    ]
