# Generated by Django 5.2.1 on 2025-06-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_content_en_page_content_en_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content_en_us',
            new_name='content_en',
        ),
    ]
