# Generated by Django 5.2.1 on 2025-06-26 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisPrompt',
            fields=[
                ('period', models.IntegerField(choices=[(1, 'Daily'), (7, 'Weekly')], primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
            ],
            options={
                'verbose_name': 'prompt',
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(choices=[(1, 'Daily'), (7, 'Weekly')])),
                ('report', models.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report',
                'ordering': ['start_date', 'end_date'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='analysis.analysisreport')),
            ],
            options={
                'verbose_name': 'summary',
                'ordering': ['report__start_date', 'report__end_date'],
            },
        ),
    ]
