# Generated by Django 5.2.1 on 2025-06-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisprompt_prompt_en_analysisprompt_prompt_ru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisprompt',
            old_name='prompt_en',
            new_name='prompt_en_us',
        ),
    ]
