# Generated by Django 5.2.1 on 2025-06-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_rename_prompt_en_analysisprompt_prompt_en_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisprompt',
            old_name='prompt_en_us',
            new_name='prompt_en',
        ),
    ]
