# Generated by Django 5.2.1 on 2025-07-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_rename_prompt_en_us_analysisprompt_prompt_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysissummary',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
