# Generated by Django 5.2.1 on 2025-07-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='percentage',
            field=models.PositiveIntegerField(),
        ),
    ]
