# Generated by Django 5.2.1 on 2025-07-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskprogress_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='percentage',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
