# Generated by Codex on 2026-01-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_tasks(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    Project = apps.get_model('projects', 'Project')
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    TaskComment = apps.get_model('tasks', 'TaskComment')

    for task in Task.objects.all():
        project = Project.objects.filter(id=task.project_id).first()
        creator = None
        if project:
            creator = project.created_by
            if creator is None:
                creator = User.objects.filter(company_id=project.company_id).first()
        if creator is None:
            creator = User.objects.first()
        assignee = creator

        task.creator_id = creator.id if creator else None
        task.assignee_id = assignee.id if assignee else None
        task.status = "DONE" if getattr(task, "is_completed", False) else "NEW"
        task.deadline = getattr(task, "due_datetime", None)
        if task.status == "DONE" and task.completed_at is None:
            task.completed_at = task.created_at
        task.save(update_fields=["creator", "assignee", "status", "deadline", "completed_at"])

    for comment in TaskComment.objects.all():
        if comment.author_id is None and comment.task_id:
            task = Task.objects.filter(id=comment.task_id).first()
            if task and task.creator_id:
                comment.author_id = task.creator_id
                comment.save(update_fields=["author"])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskprogress_percentage'),
        ('projects', '0004_project_company_not_null'),
        ('users', '0004_user_company_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='overdue_penalty_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')],
                                   default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'),
                                            ('ON_REVIEW', 'On review'), ('DONE', 'Done')],
                                   default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='task_change_logs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='change_logs', to='tasks.task')),
            ],
            options={
                'verbose_name': 'task_change_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_type', models.CharField(choices=[('MESSAGE', 'Message')], default='MESSAGE', max_length=20)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='task_results', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='results', to='tasks.task')),
            ],
            options={
                'verbose_name': 'task_result',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(backfill_tasks, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_datetime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.DeleteModel(
            name='TaskProgress',
        ),
    ]
