# Generated by Django 5.2.1 on 2026-01-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline', 'created_at'], 'verbose_name': 'task'},
        ),
    ]
