# Generated by Django 5.2.1 on 2026-01-29 12:00

from django.db import migrations, models


def set_initial_positions(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    db_alias = schema_editor.connection.alias
    tasks = (Task.objects.using(db_alias)
             .order_by('project_id', 'status', 'created_at', 'id')
             .values('id', 'project_id', 'status'))
    positions = {}
    for row in tasks:
        key = (row['project_id'], row['status'])
        positions[key] = positions.get(key, 0) + 1
        Task.objects.using(db_alias).filter(id=row['id']).update(position=positions[key])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(set_initial_positions, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position', 'deadline', 'created_at'], 'verbose_name': 'task'},
        ),
    ]
